# -*- coding: utf-8 -*-
"""Mean2D.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gZsdkplnGkohNp5OsX2YqtpmrEN0JRsk
"""

import cv2
import numpy

import numpy as np
import numpy
import cv2
import matplotlib.pyplot as plt

def func(image):
    image = cv2.imread(image)
    imgN = numpy.asarray(image)

    # imgN = meanFilter(image)
    
    fw = open('panoP.txt','w')

    for i in range(imgN.shape[0]):
        for j in range(imgN.shape[1]):
            fw.write('%s ' % imgN[i,j])
        fw.write('\n')

    fw.close()


    def meanFilter(im):
        img = im
        w = 2

        for i in range(2,im.shape[0]-2):
            for j in range(2,im.shape[1]-2):
                block = im[i-w:i+w+1, j-w:j+w+1]
                m = numpy.mean(block,dtype=numpy.float32)
                img[i][j] = int(m)
        return img

    def main():
        # with open('pano.txt','r') as f:
        #     image = []
        #     for line in f:
        #         image.append([x for x in line.split()])
        # f.close()
        
        image = numpy.genfromtxt('panoP.txt', dtype=numpy.int32)
        print(image)
        image = numpy.asarray(image)

        imgN = meanFilter(image)
    
        fw = open('panoP.txt','w')

        for i in range(imgN.shape[0]):
            for j in range(imgN.shape[1]):
                fw.write('%s ' % imgN[i,j])
            fw.write('\n')
            cv2.imwrite('output.jpg',imgN)

        fw.close()

    main()
# func('image.jpeg')